# Generated by Django 5.1.3 on 2024-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_rename_comment_videorating_reportrating_reportvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorating',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
