# Generated by Django 5.1.3 on 2024-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_videorating_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='videorating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
